### ISSUE TITLE
Palm Leaf crawl

### ISSUE THREAD

**Issue by mitra42** [internetarchive/dweb-mirror#304]
Need to be able to crawl the palmleaf 

- [ ] Run test query 5 items (example below)
  - [x] Seeing Forbidden - was epub's - handled
  - [x] Check getting all pages
  - [x] Check getting right sizes - probably not - want full size + 2000px + 400px (see below)
  - [x] Check rough size ~2.26Mb per page, ~ 100Mb (tested on 1 page only); ... target 10GB 
- [x] Need version of SD on bigger card - determine size
- [x] Copy over to SD
- [ ] Check on RPI

**Comment by mitra42** [comment]
- [ ] Test query
```
      - query: 'collection:Bali AND external-identifier:*palmleaf.org*'
        level: details
        search:
          sort: '-downloads'
          rows: 5
          level: details
```
